name: Hacker News CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn --frozen-lockfile

    - name: Check lint issue
      run: yarn lint

    - name: Check format
      run: yarn format

    - name: Run unit tests
      run: yarn test

    - name: Build
      run: yarn build
